import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import Hero from "../components/Hero"
import Skill from "../components/Skill";
import Portofolio from "../components/Portofolio";
import { useState } from "react";


export default function Home() {
 const [darkMode,setDarkMode] = useState(false)

  const handleChangeBg = ()=>{
  setDarkMode(!darkMode);
}

  return (
    <div className={darkMode?"dark":""} >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 sm:w-[32rem] sm:h-[190rem] ">
        <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>DevbyYo</h1>
            <BsFillMoonStarsFill className="cursor-pointer" onClick={()=>handleChangeBg()}/>
        </nav>
        <Hero/>
        <Skill/>  
        <Portofolio/>
      </main>
    </div>
  );
}
